[package]
name = "ktanks_server"
version = "0.1.3"
edition = "2018"
build = "build.rs"

[build-dependencies]
prost-build = "0.9"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rapier2d = { version = "*", features = [ "simd-stable","serde-serialize" ] }
macroquad = { version = "*"}
macroquad-profiler = {version = "*"}
macroquad-particles = {version = "*"}
# Logging  libraries
env_logger = {version = "*"}
log = {version = "*", features = ["max_level_debug"]}
# protobuf library
prost = "0.9"
# command line parser
clap = { version = "3.0.10", features = ["derive"] }
csv = "1.1.6"
# To control physics simulation time frame
ticktock = "0.8.0" 
serde = "1.0.135"
message-io = "*"
bincode = "*"


[dependencies.nalgebra]
version = " 0.29.0"
features =[ "convert-glam014" ,"serde-serialize"]

[dependencies.glam]
version ="0.14.0"

[profile.dev.package.rapier2d]
opt-level = 3

[profile.dev.package.macroquad]
opt-level = 3