tank_width_m = 7.0
tank_depth_m = 3.0
turret_width_m = 2.5
turret_depth_m = 0.1
turret_stiffness = 100.0
turret_damping = 40.0
turret_collider_density = 5.0
tank_collider_density = 7.0
tank_energy_max = 10000000.0
turning_power_max = 25.0
damage_max = 100.0
linear_damping = 1.0
angular_damping = 1.0
tank_engine_power_max = 100000.0
start_distance = 500.0
radar_angle_increment_max = 0.34906584
radar_width_max = 0.17453292
radar_max_detection_distance = 300.0
radar_operation_energy = 1000.0
bullet_max_range = 200.0
bullet_speed = 800.0
bullet_damage = 10.0
bullet_energy = 100000.0
power_energy_source_step = 2777.7778
zero_power_limit = 300.0
cannon_min_temp = 20.0
cannon_max_temp = 320.0
cannon_fire_temp_increase = 120.0
cannon_temp_decrease_step = 2.0
tanks_list = ["./dumb/target/wasm32-unknown-unknown/debug/dumb_comp.wasm","./simple/target/wasm32-unknown-unknown/debug/simple_comp.wasm","./hunter/target/wasm32-unknown-unknown/debug/hunter_comp.wasm"]
